const types = {
  IS_GETTING_POSITION: "IS_GETTING_POSITION",
  GET_POSITION_SUCCESS: "GET_POSITION_SUCCESS",
  GET_POSITION_FAILURE: "GET_POSITION_FAILURE",
  IS_GETTING_VENUES: "IS_GETTING_VENUES",
  GET_VENUES_SUCCESS: "GET_VENUES_SUCCESS",
  GET_VENUES_FAILURE: "GET_VENUES_FAILURE",
  UPDATE_SEARCHBAR_QUERY: "UPDATE_SEARCHBAR_QUERY"
};

export default types;
